### ISSUE TITLE
Facebook requiring https?

### ISSUE THREAD

**Issue by AMadHammer** [nbarbettini/little-aspnetcore-todo#1]
Hey not sure if this is not the right place for this given that it is a comment about the book. 

In the [chapter about FB](https://nbarbettini.gitbooks.io/little-asp-net-core-book/content/chapters/security-and-identity/add-facebook-login.html), I think FB might have changed the way they authenticate apps. 

Am I missing something or is this the case here? I understand that updates happen.

Thanks

**Comment by nbarbettini** [comment]
Yep, I think something changed here. I'm planning on tackling it in the next update to the book.

You can get around it if you skip the Facebook login stuff.

**Comment by AMadHammer** [comment]
Thank you. I will note any updates that I find on the book's github as well.
