### ISSUE TITLE
Connection to localhost refused

### ISSUE THREAD

**Issue by CedricCicada** [nbarbettini/little-aspnetcore-todo#18]
I've gotten to the point where I am ready to run the application for the first time.  In Google Chrome, I enter http://localhost:5000/todo, and I get a connection refused error.  The same thing happens under Microsoft Edge and Vivaldi.  What do I have to do to get the localhost connection accepted?

**Comment by CedricCicada** [comment]
My own idiocy.  I was thinking going to http://localhost:5000/todo would start the program.  It doesn't.  I have start it first.

**Comment by nbarbettini** [comment]
Glad you figured it out! 👍🏻
