### ISSUE TITLE
Incorrect namespace

### ISSUE THREAD

**Issue by jphellemons** [nbarbettini/little-aspnetcore-todo#2]
https://github.com/nbarbettini/little-aspnetcore-todo/blob/38eeaa1a013edceb8dfce6c0afa9d920c8ffb9e2/AspNetCoreTodo/Models/ManageUsersViewModel.cs#L4

it's in the book on page 85. Other viewmodels which are in the Models folder are also in the projectname.Models namespace. This one is not in the Models namespace.

**Comment by nbarbettini** [comment]
D'oh, fixed. Thanks!
