### ISSUE TITLE
Error after creating a new service class page 57

### ISSUE THREAD

**Issue by stephenmorton** [nbarbettini/little-aspnetcore-todo#4]
Hi, love the book. I am following it, however, have run by a problem after creating a new service class on page 57 and running the application. The error I am getting is:

```
An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot consume scoped service 'AspNetCoreTodo.Data.ApplicationDbContext' from singleton 'AspNetCoreTodo.Services.ITodoItemService'.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScoped(ScopedCallSite scopedCallSite, CallSiteValidatorState state)

Stack Query Cookies Headers
InvalidOperationException: Cannot consume scoped service 'AspNetCoreTodo.Data.ApplicationDbContext' from singleton 'AspNetCoreTodo.Services.ITodoItemService'.
```

There aren't any errors showing up in code or on the output window when debugging the application. However, clicking on the todo url brings up the above error.
Thanks in advance for your help.
Steve

**Comment by stephenmorton** [comment]
You are spot on. Sorry, I didn’t see that I needed to change this line from:
services.AddSingleton<ITodoItemService, TodoItemService>();
to
services.AddScoped<ITodoItemService, TodoItemService>();
I missed the AddScoped bit. Thanks again for an excellent book and for your help.

Regards,

Stephen G Morton
P 1300 484 511 | D 02 8488 3151 | M 0418 111 068

**Comment by nbarbettini** [comment]
Glad that worked!
