### ISSUE TITLE
Try it out... not working - just gone through the steps as mentioned but following error came

### ISSUE THREAD

**Issue by noorrocks** [nbarbettini/little-aspnetcore-todo#6]
[ 
Try it out
Make sure you have the .NET Core SDK installed on your machine. Then do:
](https://github.com/nbarbettini/little-aspnetcore-todo/blob/master/README.md)
```
git clone https://github.com/nbarbettini/little-aspnetcore-todo.git
cd little-aspnetcore-todo
dotnet  #run
```

Noor@DATASCAPE  C\..\..\..\little-aspnetcore-todo   master ≣  dotnet run .
Couldn't find a project to run. Ensure a project exists in C:\#Noor\dotnetcore\littleaspcoredotnetbook\little-aspnetcore-todo, or pass the path to the project using --project.

**Comment by jahbenjah** [comment]
@noorrocks
 Changes your cd comando by
 
cd little-aspnetcore-todo /AspNetCoreTodo

In this directory is the .csproj dile needed ti run the project

**Comment by nbarbettini** [comment]
@jahbenjah is correct, you need to cd one more time to get into the `AspNetCoreTodo` folder.
